language: clojure

env:
  global:
  # build a tag that consist of git commit hash and ISO-8601 
  # compatible UTC timestamp separated by "-"
  - TAG=${git rev-parse --short HEAD}-${date --utc +%Y%m%dT%H%M%SZ}
  - REGION=eu-central-1
  # Name of the project/docker image
  - NAME=clojure-graphql-api
  - AWS_QA=257169857724
  - AWS_PROD=257169857724
  # ECR repository
  - ECR=257169857724.dkr.ecr.${REGION}.amazonaws.com
  - IMAGE=${ECR}/${NAME}:${TAG}

services:
  - docker
  
jdk:
- oraclejdk11

branches:
  only:
  - master

install:
# Install AWS CLI
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin

# install all the project dependencies
- lein deps

before_script:
# Run various static analysis tools
- lein eastwood
- lein ancient
- lein kibit

# Run unit tests
- lein test

# Generate and publish code coverage report
- lein cloverage --codecov || true
- bash <(curl -s https://codecov.io/bash)

script:
# Build uberjar and create docker image
- lein uberjar

- docker build -t ${NAME} .
- docker tag ${NAME} ${IMAGE}

# Validate docker image
- docker run -d -p 8888:8888 --name ${NAME} ${NAME}
- docker ps | grep -q ${NAME}

after_success:
# Push image to ECR
- travis-ci/docker_push.sh

