language: clojure

env:
  global:
  - TAG=`date --utc +%Y%m%dT%H%M%SZ`
  - IMAGE=clojure-graphql-api

services:
  - docker
  
jdk:
- oraclejdk11

branches:
  only:
  - master

before_script:
- lein eastwood
- lein test

script:
- lein uberjar

- docker --version
- docker build -t ${IMAGE} .
- docker run -d -p 8888:8888 --name ${IMAGE} ${IMAGE}
- docker ps | grep -q ${IMAGE}

- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --region eu-central-1 --no-include-email | sed 's|https://||') 

- docker tag clojure-graphql-api:latest 257169857724.dkr.ecr.eu-central-1.amazonaws.com/${IMAGE}:${TAG}
- docker push 257169857724.dkr.ecr.eu-central-1.amazonaws.com/${IMAGE}:${TAG}

after_success:
- lein ancient
- lein kibit
- lein cloverage --codecov
- bash <(curl -s https://codecov.io/bash)
