language: clojure

env:
  global:
  - COMMIT_HASH=`git rev-parse --short HEAD`
  - TIMESTAMP=`date --utc +%Y%m%dT%H%M%SZ`
  # build a tag that consist of git commit hash and ISO-8601 
  # compatible UTC timestamp separated by "-"
  - TAG=${COMMIT_HASH}-${TIMESTAMP}
  - REGION=eu-central-1
  - NAME=clojure-graphql-api
  - AWS_QA=257169857724
  - AWS_PROD=257169857724
  - ECR=257169857724.dkr.ecr.${REGION}.amazonaws.com
  - IMAGE=${ECR}/${NAME}:${TAG}

services:
  - docker
  
jdk:
- oraclejdk11

branches:
  only:
  - master

install:
# Install AWS CLI
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin

script:
# run clojure specific CI pipeline commands. You can
# implement any other JVM language pipeline on top of
# this travis file e.g. travis-ci/script_scala.sh etc.
- travis-ci/script_clojure.sh

- docker build -t ${NAME} .
- docker tag ${NAME} ${IMAGE}

# Validate docker image (TODO make sure it works!)
- docker run -d -p 8888:8888 --name ${NAME} ${NAME}
- docker ps | grep -q ${NAME}

after_success:
# Push image to ECR
- travis-ci/docker_push.sh

